### ISSUE TITLE
Error handling when Redis server is unavailable

### ISSUE THREAD

**Issue by epot** [hootsuite/akka-persistence-redis#30]
Hello,

I am not sure at all about my comments here, so feel free to let me know if I misunderstood something. I am trying to see how this plugin behaves if the Redis server becomes unavailable for a few secondes (in case the primary node restarts for instance). Currently, it seems that it raises a onPersistRejected and just log a warning. My understanding of the Akka doc (http://doc.akka.io/docs/akka/current/scala/persistence.html) is that I would rather expect a onPersistFailure  here and the actor dying. On top of that, wouldn't it be better to use the AsyncWriteJournal circuit breaker in order to have some timeout/retry mechanism before raising an error ? In case of a connection blip, I do not think there is any need to raise an error or to kill the actor but maybe I am wrong.

What do you think ?

Cheers,
Emmanuel

**Comment by ssong-van** [comment]
Great question. I agree that `onPersistFailure` is more appropriate on Redis connection failure. The reason for raising `onPersistRejected` is because how the plugin recovers a failed Redis operation here: https://github.com/hootsuite/akka-persistence-redis/blob/master/src/main/scala/com/hootsuite/akka/persistence/redis/journal/RedisJournal.scala#L65 and becomes successful future of failed try. Then it goes through https://github.com/akka/akka/blob/9d2bec7f232b628cc087231af75e457072823e61/akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala#L101 and raise `onPersistRejected`

I think not recovering on connection failure and let it bubble up to Akka would work. 

As for circuit breaker, it makes sense to retry few times on connection failure. Looks like it's already done in Akka Persistence: https://github.com/akka/akka/blob/9d2bec7f232b628cc087231af75e457072823e61/akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala#L71

**Comment by epot** [comment]
Ok, thanks for your insights. Is is something you plan to work on ? I am definitely interested in this feature, as I am afraid I cannot go to production with the current behaviour, so I will look into it if it is not in your plan. I am just afraid not to understand all the flows for the moment, so my implementation may be not perfect.

**Comment by epot** [comment]
I tried a very dummy:

`batchOperations
      .map(Success(_))
      .recover {
        case ex if ex == NoConnectionException => throw(ex) // let the no connection exception bubble up to Akka
        case ex => Failure(ex)
      }`

but it does not behave as expect. A `onPersistFailure` is immediately raised and my actor exits.

**Comment by ssong-van** [comment]
Getting `onPersistFailure` is what we wanted isn't it? Circuit breaker does not retry a failed request. It blocks future requests to fail fast for configured period of time. 

`onPersistFailure` can be overridden. Since the actor will be killed, how about sending a write message to another actor to retry after a configurable delay? Maybe try BackoffSupervisor? http://doc.akka.io/docs/akka/2.4.17/scala/persistence.html#Failures

Another solution could be implementing a retry logic in the plugin. Take a look at Cassandra plugin if you are interested. They have different retry policy for read and write. I'd be interested in implementing something like this but no guarantee on delivery date. We always welcome PRs!

**Comment by epot** [comment]
Yes, my bad. I misunderstood your first post and thought that Akka Persistence implemented a retry mechanism. I will look at the cassandra plugin and see if I can try to implement something similar. Thanks !

**Comment by ssong-van** [comment]
Oh yeah my first post is confusing indeed. Let me know if you have any further questions.

**Comment by epot** [comment]
Going back to this point :). I looked at the cassandra plugin but as far as I understand the retry logic is implemented in the Cassandra Java Driver, am I correct ? Do you agree this should be done in rediscala and not in akka-persistence-redis if we wanted a similar behavior with this plugin ?

**Comment by epot** [comment]
What do you think of something like this ? I would need to replicate this behavior when saving snapshot and recovering, but I wanted your point of view first. I would also put the values in a configuration file as well.

**Comment by epot** [comment]
I did some improvements, I would really be interested to know what you think of the current state. Keep me posted!

**Comment by ssong-van** [comment]
Thanks for the commit. I'll review this today.

**Comment by ssong-van** [comment]
Re: Cassandra plugin
You are totally right, the logic is in the Java driver. I didn't realize this. It would be nice if Redis driver (rediscala) had retries. One could also argue the driver should be generic and the caller should decide to retry or not.

**Comment by epot** [comment]
I guess this can be closed with the 0.8.0 release. Thanks!!

**Comment by epot** [comment]
Sorry it's me again :). Is it going to be released with Scala 2.11 support? I cannot find it on maven central for the moment :-/.

**Comment by ssong-van** [comment]
I didn't release 0.8.0 yet. It will be available on Bintray later today.

**Comment by ssong-van** [comment]
0.8.0 should be available on Bintray and Maven for Scala 2.11 and 2.12.

**Comment by epot** [comment]
Yes I have already deployed my app with the new version in a test environment. Thanks!!
